// Dados iniciais (seed): clientes adicionados via código/push.
// Cada item precisa de um "id" fixo e único (ex: "empresa-nome-do-cliente"),
// assim novos pushes só adicionam o que for novo, sem duplicar ou apagar
// edições feitas na interface pelo usuário.
const SEED_CLIENTES = [
  {
    id: "centro-odonto",
    nome: "Centro Odonto",
    empresa: "Centro Odonto",
    telefone: "+55 62 98503-7650",
    email: "",
    servico: "Site institucional",
    status: "andamento",
    valor: 1500,
    pagamento: "pendente",
    obs: "Clínica odontológica independente (não é rede), Anápolis-GO. Endereço: R. Luís França, 234 - Jundiaí, Anápolis - GO, 75110-760. Avaliação 4,9 (79 avaliações). Sem site próprio — aparece só em diretórios agregadores (Doctoralia, DentMap, Anápolis Club). Contato só por WhatsApp/telefone.\n\nInstitucional + agendamento WhatsApp. Faixa negociável: R$1.200–1.500.\n\nAbordagem sugerida (WhatsApp): \"Olá, equipe da Centro Odonto, tudo bem? Meu nome é João Vittor, sou desenvolvedor na Evodev Studio, baseado aqui na região de Pires do Rio / Anápolis. Estava buscando indicações de clínicas odontológicas de confiança em Jundiaí e encontrei o perfil de vocês com excelentes avaliações no Google Maps (média de 4.9!). Vi que vocês são uma clínica independente super conceituada, mas notei que ainda não possuem um site institucional próprio para agendamentos e apresentação dos tratamentos (implantes, estética, etc.). Hoje em dia, muitos pacientes buscam no Google antes de fechar tratamentos de maior valor, e a falta de um site próprio faz com que vocês percam espaço para redes de franquias que têm páginas pesadas na internet. Eu crio páginas focadas em conversão, agendamento facilitado via WhatsApp e apresentação profissional da equipe médica para o mercado de saúde. Poderíamos agendar uma conversa rápida de 5 minutos, sem compromisso, para eu lhes mostrar como um site exclusivo pode aumentar as consultas particulares de vocês? Obrigado pela atenção!\" — enviar junto com demo do site.",
    origem: "pesquisa_web",
  },
  {
    id: "poesia-arquitetura",
    nome: "Poesia Arquitetura",
    empresa: "Poesia Arquitetura",
    telefone: "+55 62 99306-6273",
    email: "",
    servico: "Site institucional",
    status: "andamento",
    valor: 1400,
    pagamento: "pendente",
    obs: "Escritório de arquitetura, Anápolis-GO. Endereço: London Eye Offices - Av. Sen. José Lourenço Dias - St. Central, Anápolis - GO, 75020-010. Redes: linktr.ee/poesiaarquitetura. Avaliação 5,0 (13 avaliações). Só Linktree, sem site dedicado — forte fit pro portfólio/institucional, já que arquitetura vive de mostrar projeto visualmente.\n\nPortfólio visual de projetos. Faixa negociável: R$1.200–1.400.\n\nAbordagem sugerida (WhatsApp): \"Olá, [Nome do Responsável / Equipe do Poesia Arquitetura], tudo bem? Me chamo João Vittor, sou desenvolvedor aqui no estado de Goiás (Evodev Studio) e acompanho muito o mercado de arquitetura de Anápolis. Estava avaliando os projetos incríveis e a excelente reputação que vocês construíram no Google Maps (nota máxima!) e notei que vocês utilizam o Linktree como ponto principal de contato. Como o trabalho de vocês é extremamente visual e de alto padrão, o Linktree acaba limitando a experiência do cliente ao não exibir de cara o portfólio de vocês de forma profissional, fluida e rápida. Eu desenvolvo plataformas de portfólio sob medida, rápidas e focadas em encantar o cliente logo no primeiro clique, trazendo muito mais valor aos projetos de interiores e residenciais de vocês. Vocês teriam 5 minutos nesta semana para eu mostrar como podemos transformar seu Linktree em um site exclusivo que faça jus à qualidade dos seus projetos? Um abraço!\" — enviar junto com demo do site.",
    origem: "pesquisa_web",
  },
  {
    id: "anderson-junio-arquiteto",
    nome: "Anderson Junio Arquiteto e Urbanista",
    empresa: "Anderson Junio Arquiteto e Urbanista",
    telefone: "+55 62 99466-0696",
    email: "",
    servico: "Site institucional",
    status: "andamento",
    valor: 1800,
    pagamento: "pendente",
    obs: "Arquiteto/urbanista independente, mais de 10 anos de mercado, atuação residencial/comercial/industrial. Anápolis-GO. Endereço: Condomínio Residencial Havilah - R. 22, Q. A - Nº 38, bloco 05, A44 - Chácaras Americanas, Anápolis - GO, 75103-205. Redes: linktr.ee/andersonjunio_arq · Instagram @anderson_arquiteto (2.107 seguidores) · LinkedIn · Facebook. Avaliação 5,0 (26 avaliações). Sem site próprio, só Linktree/redes sociais. Junto com Poesia Arquitetura, indica que arquitetos independentes em Anápolis sem site são um nicho recorrente bom pra prospectar.\n\nPortfólio + múltiplas frentes (residencial/comercial/industrial), mais páginas. Faixa negociável: R$1.500–1.800.\n\nAbordagem sugerida (WhatsApp): \"Olá, [Nome do Responsável / Equipe do Anderson Junio], tudo bem? Me chamo João Vittor, sou desenvolvedor aqui no estado de Goiás (Evodev Studio) e acompanho muito o mercado de arquitetura de Anápolis. Estava avaliando os projetos incríveis e a excelente reputação que vocês construíram no Google Maps (nota máxima!) e notei que vocês utilizam o Linktree como ponto principal de contato. Como o trabalho de vocês é extremamente visual e de alto padrão, o Linktree acaba limitando a experiência do cliente ao não exibir de cara o portfólio de vocês de forma profissional, fluida e rápida. Eu desenvolvo plataformas de portfólio sob medida, rápidas e focadas em encantar o cliente logo no primeiro clique, trazendo muito mais valor aos projetos de interiores e residenciais de vocês. Vocês teriam 5 minutos nesta semana para eu mostrar como podemos transformar seu Linktree em um site exclusivo que faça jus à qualidade dos seus projetos? Um abraço!\" — enviar junto com demo do site.",
    origem: "pesquisa_web",
  },
  {
    id: "pedro-xavier-advogados",
    nome: "Pedro Xavier Advogados",
    empresa: "Pedro Xavier Advogados",
    telefone: "+55 62 3702-0999",
    email: "",
    servico: "Site institucional",
    status: "andamento",
    valor: 2500,
    pagamento: "pendente",
    obs: "Escritório de advocacia, Anápolis-GO. Endereço: R. do Carmo, 9 - Jundiaí, Anápolis - GO, 75113-050. Avaliação 4,9 (244 avaliações — volume muito alto pro setor). Sem site próprio — só Jusbrasil, CNPJ.biz e Facebook modesto (113 curtidas). Negócio grande e ativo sem presença digital própria. Pacote institucional cotado: R$1.200 (área de atuação, prova social com as 244 avaliações, contato direto).\n\nInstitucional jurídico, compliance visual OAB, alta prova social (244 avaliações). Faixa negociável: R$1.800–2.500.\n\nAbordagem sugerida (WhatsApp): \"Olá, Dr. Pedro Xavier e equipe, tudo bem? Me chamo João Vittor, sou desenvolvedor e fundador da Evodev Studio. Estava analisando os escritórios de advocacia mais influentes de Anápolis e o Pedro Xavier Advogados me chamou muito a atenção: vocês têm um volume impressionante de avaliações cinco estrelas (mais de 240!), o que mostra uma autoridade gigantesca na região. Contudo, reparei que essa forte autoridade ainda não está consolidada em um domínio próprio na internet (hoje o escritório depende de páginas de terceiros como o Jusbrasil e redes sociais). Para um escritório com esse porte e reputação, ter um site institucional limpo, seguro e elegante é fundamental para passar segurança a novos clientes corporativos e de alta renda, além de centralizar as áreas de atuação e o contato direto de forma organizada. Desenvolvo sites institucionais modernos específicos para o setor jurídico, respeitando as normas da OAB e focando em credibilidade. Podemos agendar uma ligação rápida de 5 minutos para que eu mostre como podemos estruturar essa presença digital do escritório? Atenciosamente, João Vittor C. Castro\" — enviar junto com demo do site.",
    origem: "pesquisa_web",
  },
];
