// Dados iniciais (seed): clientes adicionados via código/push.
// Cada item precisa de um "id" fixo e único (ex: "empresa-nome-do-cliente"),
// assim novos pushes só adicionam o que for novo, sem duplicar ou apagar
// edições feitas na interface pelo usuário.
const SEED_CLIENTES = [
  {
    id: "centro-odonto",
    nome: "Centro Odonto",
    empresa: "Centro Odonto",
    telefone: "+55 62 98503-7650",
    email: "",
    servico: "Site institucional",
    status: "andamento",
    valor: "",
    pagamento: "pendente",
    obs: "Clínica odontológica independente (não é rede), Anápolis-GO. Endereço: R. Luís França, 234 - Jundiaí, Anápolis - GO, 75110-760. Avaliação 4,9 (79 avaliações). Sem site próprio — aparece só em diretórios agregadores (Doctoralia, DentMap, Anápolis Club). Contato só por WhatsApp/telefone.",
    origem: "pesquisa_web",
  },
  {
    id: "poesia-arquitetura",
    nome: "Poesia Arquitetura",
    empresa: "Poesia Arquitetura",
    telefone: "+55 62 99306-6273",
    email: "",
    servico: "Site institucional",
    status: "andamento",
    valor: "",
    pagamento: "pendente",
    obs: "Escritório de arquitetura, Anápolis-GO. Endereço: London Eye Offices - Av. Sen. José Lourenço Dias - St. Central, Anápolis - GO, 75020-010. Redes: linktr.ee/poesiaarquitetura. Avaliação 5,0 (13 avaliações). Só Linktree, sem site dedicado — forte fit pro portfólio/institucional, já que arquitetura vive de mostrar projeto visualmente.",
    origem: "pesquisa_web",
  },
  {
    id: "anderson-junio-arquiteto",
    nome: "Anderson Junio Arquiteto e Urbanista",
    empresa: "Anderson Junio Arquiteto e Urbanista",
    telefone: "+55 62 99466-0696",
    email: "",
    servico: "Site institucional",
    status: "andamento",
    valor: "",
    pagamento: "pendente",
    obs: "Arquiteto/urbanista independente, mais de 10 anos de mercado, atuação residencial/comercial/industrial. Anápolis-GO. Endereço: Condomínio Residencial Havilah - R. 22, Q. A - Nº 38, bloco 05, A44 - Chácaras Americanas, Anápolis - GO, 75103-205. Redes: linktr.ee/andersonjunio_arq · Instagram @anderson_arquiteto (2.107 seguidores) · LinkedIn · Facebook. Avaliação 5,0 (26 avaliações). Sem site próprio, só Linktree/redes sociais. Junto com Poesia Arquitetura, indica que arquitetos independentes em Anápolis sem site são um nicho recorrente bom pra prospectar.",
    origem: "pesquisa_web",
  },
  {
    id: "pedro-xavier-advogados",
    nome: "Pedro Xavier Advogados",
    empresa: "Pedro Xavier Advogados",
    telefone: "+55 62 3702-0999",
    email: "",
    servico: "Site institucional",
    status: "andamento",
    valor: 1200,
    pagamento: "pendente",
    obs: "Escritório de advocacia, Anápolis-GO. Endereço: R. do Carmo, 9 - Jundiaí, Anápolis - GO, 75113-050. Avaliação 4,9 (244 avaliações — volume muito alto pro setor). Sem site próprio — só Jusbrasil, CNPJ.biz e Facebook modesto (113 curtidas). Negócio grande e ativo sem presença digital própria. Pacote institucional cotado: R$1.200 (área de atuação, prova social com as 244 avaliações, contato direto).",
    origem: "pesquisa_web",
  },
];
