// Gerado por scripts/build-leads-seed.js a partir de data/leads_seed.csv
// Não edite à mão — rode o script novamente para atualizar.
const SEED_LEADS = [
  {
    "id": "viva-odonto-goiania",
    "nome": "Viva Odonto",
    "nicho": "Odontologia",
    "cidade": "Goiânia",
    "telefone": "+55 62 99983-9130",
    "redes_sociais": "@vivaodonto.goiania",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site próprio confirmado via busca (apenas Instagram). Setor Goiânia Viva.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.633Z"
  },
  {
    "id": "plena-saude-e-beleza-anapolis",
    "nome": "Plena Saúde e Beleza",
    "nicho": "Estética",
    "cidade": "Anápolis",
    "telefone": "+55 62 99655-0988",
    "redes_sociais": "@plena.saudebeleza",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Clínica ativa desde 2005 (Plena Clínica Integrada de Medicina e Estética Ltda), Rua Barão do Rio Branco 573, Centro. Sem site próprio confirmado.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "spallita-anapolis",
    "nome": "Spallitá",
    "nicho": "Estética",
    "cidade": "Anápolis",
    "telefone": "+55 62 99314-3551",
    "redes_sociais": "@spallita",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone fixo também: (62) 3706-1445. Sem site próprio confirmado (só Facebook/Instagram).",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "marfim-ambientes-goiania",
    "nome": "Marfim Ambientes",
    "nicho": "Marcenaria/Móveis planejados",
    "cidade": "Goiânia",
    "telefone": "+55 62 98643-0412",
    "redes_sociais": "@marfimambientes",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Móveis planejados alto padrão, atua em Goiânia/Aparecida de Goiânia. Sem site próprio confirmado.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "c-a-marmoraria-anapolis",
    "nome": "C&A Marmoraria",
    "nicho": "Marmoraria",
    "cidade": "Anápolis",
    "telefone": "+55 62 99306-3063",
    "redes_sociais": "",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Bairro de Lourdes/Centro. Só aparece em diretórios + WhatsApp, sem site próprio.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "marmoraria-anapolina-anapolis",
    "nome": "Marmoraria Anapolina",
    "nicho": "Marmoraria",
    "cidade": "Anápolis",
    "telefone": "+55 62 99297-4237",
    "redes_sociais": "@marmorariaanapolina",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Mais de 20 anos no mercado, CNPJ ativo. Sem site próprio confirmado (Facebook/Instagram).",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "marmoraria-brasil-anapolis",
    "nome": "Marmoraria Brasil",
    "nicho": "Marmoraria",
    "cidade": "Anápolis",
    "telefone": "+55 62 3771-3495",
    "redes_sociais": "@marmorariabrasill1",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Av. Pedro Ludovico, 3049. Sem site próprio confirmado, só Instagram.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "marceneiro-goiania-goiania",
    "nome": "Marceneiro Goiânia",
    "nicho": "Marcenaria",
    "cidade": "Goiânia",
    "telefone": "+55 62 99232-8423",
    "redes_sociais": "",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "Mais de 30 anos no ramo. Site atual é uma página gratuita do Google Sites (sites.google.com) — conta como site de baixo nível, não site profissional.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "recanto-santa-cecilia-eventos-anapolis",
    "nome": "Recanto Santa Cecília Eventos",
    "nicho": "Buffet/Eventos",
    "cidade": "Anápolis",
    "telefone": "+55 62 99980-0221",
    "redes_sociais": "@recantosantacecilia",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Espaço para eventos. Sem site próprio confirmado, só Instagram.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "celebrare-casa-de-eventos-anapolis",
    "nome": "Celebrare Casa de Eventos",
    "nicho": "Buffet/Eventos",
    "cidade": "Anápolis",
    "telefone": "+55 62 99182-2474",
    "redes_sociais": "@celebrarecasadeventos",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Aluguel de espaço para festas/eventos. Sem site próprio confirmado, só Instagram.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "otica-alta-vista-goiania",
    "nome": "Ótica Alta Vista",
    "nicho": "Ótica",
    "cidade": "Goiânia",
    "telefone": "+55 62 98530-0331",
    "redes_sociais": "@otica.altavista",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Baixo",
    "status": "a_contatar",
    "observacoes": "Instagram e WhatsApp confirmados via busca; site próprio não encontrado, apenas linktr.ee/oticaaltavista (site de baixo nível)",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "bb-semijoias-goiania-goiania",
    "nome": "BB Semijoias Goiânia",
    "nicho": "Joalheria",
    "cidade": "Goiânia",
    "telefone": "+55 62 98583-2889",
    "redes_sociais": "@bbsemijoias1",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "WhatsApp e Instagram confirmados via busca; nenhum site .com.br próprio encontrado, vende só por Instagram/WhatsApp",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "luxury-acessorios-goiania",
    "nome": "Luxury Acessórios",
    "nicho": "Joalheria",
    "cidade": "Goiânia",
    "telefone": "+55 62 3088-5945",
    "redes_sociais": "@luxuryacessorioss",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone via cadastro empresarial e Instagram (21 mil seguidores) confirmados; sem site próprio encontrado nas buscas",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "ouro-forte-joias-goiania",
    "nome": "Ouro Forte Joias",
    "nicho": "Joalheria",
    "cidade": "Goiânia",
    "telefone": "+55 62 98601-9020",
    "redes_sociais": "@ourofortegyn",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone/WhatsApp e Instagram confirmados via busca; nenhum site oficial encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "junio-joias-e-relogios-goiania",
    "nome": "Junio Joias e Relógios",
    "nicho": "Joalheria",
    "cidade": "Goiânia",
    "telefone": "+55 62 98468-1022",
    "redes_sociais": "@juniojoiasgo",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "WhatsApp e Instagram confirmados via busca; sem site próprio, peças sob encomenda via WhatsApp",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "haus-tattoo-goiania",
    "nome": "Haus Tattoo",
    "nicho": "Estúdio de tatuagem",
    "cidade": "Goiânia",
    "telefone": "+55 62 98309-9408",
    "redes_sociais": "@haustattoo",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "WhatsApp, Instagram e página no Facebook confirmados; nenhum site oficial encontrado nas buscas",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "nishimura-tattoo-studio-goiania",
    "nome": "Nishimura Tattoo Studio",
    "nicho": "Estúdio de tatuagem",
    "cidade": "Goiânia",
    "telefone": "+55 62 98544-9030",
    "redes_sociais": "@nishimuratattoostudio",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "WhatsApp e Instagram confirmados via busca e matéria do blog Tattoo2me; sem site oficial dedicado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "garuda-tatuagens-goiania",
    "nome": "Garuda Tatuagens",
    "nicho": "Estúdio de tatuagem",
    "cidade": "Goiânia",
    "telefone": "+55 62 3095-1247",
    "redes_sociais": "@garudatatuagens",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone e Instagram confirmados via busca; nenhum site próprio encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "robinho-tattoo-lab-goiania",
    "nome": "Robinho Tattoo Lab",
    "nicho": "Estúdio de tatuagem",
    "cidade": "Goiânia",
    "telefone": "+55 62 98305-4383",
    "redes_sociais": "@robinhotattoo",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Baixo",
    "status": "a_contatar",
    "observacoes": "WhatsApp confirmado via página do Facebook do estúdio e Instagram do tatuador; site é apenas linktr.ee/Tattoolab (site de baixo nível)",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "cleber-roberto-fotografia-goiania",
    "nome": "Cleber Roberto Fotografia",
    "nicho": "Fotografia",
    "cidade": "Goiânia",
    "telefone": "+55 62 98145-2406",
    "redes_sociais": "@cleberrobertoph",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "WhatsApp e Instagram confirmados via matéria da Curta Mais sobre fotógrafos de ensaio gestante em Goiânia; sem site próprio encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "otica-vip-anapolis",
    "nome": "Ótica Vip",
    "nicho": "Ótica",
    "cidade": "Anápolis",
    "telefone": "+55 62 3321-0227",
    "redes_sociais": "@oticasvipofc",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site próprio identificado nas buscas (apenas diretórios); Instagram e telefone confirmados em diretórios locais.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "visotica-anapolis",
    "nome": "Visótica",
    "nicho": "Ótica",
    "cidade": "Anápolis",
    "telefone": "+55 62 3099-3090",
    "redes_sociais": "@visotica_anapolis",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Loja local (não é franquia nacional); sem site próprio encontrado, Instagram com cerca de 21 mil seguidores confirmado.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "otica-costa-anapolis",
    "nome": "Ótica Costa",
    "nicho": "Ótica",
    "cidade": "Anápolis",
    "telefone": "+55 62 99280-3287",
    "redes_sociais": "@oticacostaa",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site próprio encontrado; Instagram e Facebook confirmados.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "joalheria-itagiba-anapolis",
    "nome": "Joalheria Itagiba",
    "nicho": "Joalheria",
    "cidade": "Anápolis",
    "telefone": "+55 62 3318-1505",
    "redes_sociais": "@joalheriaitagiba",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Joalheria tradicional (desde 1949/fundada 1986); sem site .com.br encontrado, Instagram e Facebook confirmados.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "pardal-tattoo-studio-anapolis",
    "nome": "Pardal Tattoo Studio",
    "nicho": "Estúdio de tatuagem",
    "cidade": "Anápolis",
    "telefone": "+55 62 9217-7602",
    "redes_sociais": "@pardaltattoo",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Cerca de 17 mil seguidores no Instagram; sem site próprio encontrado, Facebook e WhatsApp confirmados.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "new-old-tattoo-art-anapolis",
    "nome": "New Old Tattoo Art",
    "nicho": "Estúdio de tatuagem",
    "cidade": "Anápolis",
    "telefone": "+55 62 9255-9532",
    "redes_sociais": "@newoldtattoo",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Baixo",
    "status": "a_contatar",
    "observacoes": "Usa apenas link-in-bio (heylink.me) em vez de site próprio; Instagram, Facebook e telefone confirmados.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "seth-tattoo-anapolis",
    "nome": "Seth Tattoo",
    "nicho": "Estúdio de tatuagem",
    "cidade": "Anápolis",
    "telefone": "+55 62 99332-8690",
    "redes_sociais": "@sethtattoo_",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site oficial encontrado; Instagram com cerca de 14 mil seguidores e Facebook confirmados.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "perola-fotografia-anapolis",
    "nome": "Perola Fotografia",
    "nicho": "Fotografia",
    "cidade": "Anápolis",
    "telefone": "+55 62 9227-2709",
    "redes_sociais": "Facebook: Perola Fotografia",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Fotografia de casamentos, 15 anos e newborn; sem site próprio encontrado, telefone e Facebook confirmados.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "focus-locacao-de-ternos-e-fotografia-anapolis",
    "nome": "Focus Locação de Ternos e Fotografia",
    "nicho": "Fotografia",
    "cidade": "Anápolis",
    "telefone": "+55 62 99331-1299",
    "redes_sociais": "@focusternosanapolis",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Locação de ternos com serviço de fotografia para casamentos/eventos; sem site próprio confirmado, Instagram e Facebook confirmados.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "wanessa-bueno-confeitaria-anapolis",
    "nome": "Wanessa Bueno Confeitaria",
    "nicho": "Confeitaria",
    "cidade": "Anápolis",
    "telefone": "+55 62 99201-9330",
    "redes_sociais": "@wanessa.bueno.confeitaria",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "WhatsApp confirmado em post do próprio Instagram; sem site próprio encontrado, Facebook também confirmado.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.634Z"
  },
  {
    "id": "confeitaria-delicias-da-vivi-anapolis",
    "nome": "Confeitaria Delícias da Vivi",
    "nicho": "Confeitaria",
    "cidade": "Anápolis",
    "telefone": "+55 62 99132-5746",
    "redes_sociais": "Facebook: Confeitaria Delícias da vivi",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone confirmado em diretório local; sem site próprio encontrado, presença confirmada no Facebook.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "festinha-express-goiania",
    "nome": "Festinha Express",
    "nicho": "Decoração de festas",
    "cidade": "Goiânia",
    "telefone": "+55 62 98135-2901",
    "redes_sociais": "@festinha_express",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site próprio encontrado; apenas Instagram (64 mil seguidores) confirmado nas buscas",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "valeria-junqueira-festas-goiania",
    "nome": "Valéria Junqueira Festas",
    "nicho": "Decoração de festas",
    "cidade": "Goiânia",
    "telefone": "+55 62 99934-8385",
    "redes_sociais": "@valeriajunqueirafestas",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone e Instagram/Facebook confirmados; nenhum site .com.br dedicado encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "opcao-cenografia-goiania",
    "nome": "Opção Cenografia",
    "nicho": "Decoração de festas",
    "cidade": "Goiânia",
    "telefone": "+55 62 9918-2942",
    "redes_sociais": "@opcaocenografia",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Contato e Instagram com 7,6 mil seguidores confirmados; não achou site próprio",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "cris-medeiros-festas-goiania",
    "nome": "Cris Medeiros Festas",
    "nicho": "Decoração de festas",
    "cidade": "Goiânia",
    "telefone": "+55 62 3296-4141",
    "redes_sociais": "@crismedeirosfestas",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone via listagem de empresas e perfil no Instagram/Facebook confirmados; sem site dedicado encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "ambientart-paisagismo-goiania",
    "nome": "Ambientart Paisagismo",
    "nicho": "Paisagismo",
    "cidade": "Goiânia",
    "telefone": "+55 62 99849-3373",
    "redes_sociais": "@jardimverticalgoiania",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Baixo",
    "status": "a_contatar",
    "observacoes": "Site encontrado é uma página gratuita no Wix; telefone/whatsapp e Instagram/Facebook confirmados",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "sidney-jardineiro-goiania",
    "nome": "Sidney Jardineiro",
    "nicho": "Paisagismo",
    "cidade": "Goiânia",
    "telefone": "+55 62 99255-5054",
    "redes_sociais": "@sidneyjardineiro",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone/whatsapp e perfil no Instagram confirmados; nenhum site próprio encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "green-garden-jardins-verticais-goiania",
    "nome": "Green&Garden Jardins Verticais",
    "nicho": "Paisagismo",
    "cidade": "Goiânia",
    "telefone": "+55 62 98117-8481",
    "redes_sociais": "@greengarden_art",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone e Instagram com 15 mil seguidores confirmados; sem site dedicado encontrado nas buscas",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "elegance-buffet-anapolis",
    "nome": "Elegance Buffet",
    "nicho": "Decoração de festas",
    "cidade": "Anápolis",
    "telefone": "+55 62 99164-6011",
    "redes_sociais": "@elegancebuffet",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Buffet e organização de festas sem site próprio; presença apenas via Instagram e diretórios locais",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "gasarope-festas-infantis-e-eventos-anapolis",
    "nome": "Gasarope Festas Infantis e Eventos",
    "nicho": "Decoração de festas",
    "cidade": "Anápolis",
    "telefone": "+55 62 99168-4448",
    "redes_sociais": "@gasaropeeventos",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Baixo",
    "status": "a_contatar",
    "observacoes": "Site encontrado é apenas página gratuita Webnode de baixo nível, sem domínio próprio profissional",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "mobilite-studio-de-pilates-anapolis",
    "nome": "Mobilité Studio de Pilates",
    "nicho": "Pilates/Personal",
    "cidade": "Anápolis",
    "telefone": "+55 62 98134-2094",
    "redes_sociais": "@pilates_anapolis",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site oficial encontrado; telefone e Instagram confirmados em múltiplas buscas",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "center-pilates-anapolis-anapolis",
    "nome": "Center Pilates Anápolis",
    "nicho": "Pilates/Personal",
    "cidade": "Anápolis",
    "telefone": "+55 62 99153-7206",
    "redes_sociais": "@centerpilatesanapolis",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Presença apenas via Instagram e Facebook, sem site dedicado localizado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "debora-cristina-nutricionista-anapolis-anapolis",
    "nome": "Débora Cristina - Nutricionista Anápolis",
    "nicho": "Nutricionista",
    "cidade": "Anápolis",
    "telefone": "+55 62 99923-9737",
    "redes_sociais": "@nutri.deboraa",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Atendimento particular (emagrecimento/hipertrofia); sem site próprio, apenas Instagram com cerca de 36 mil seguidores",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "pet-stop-anapolis-anapolis",
    "nome": "Pet Stop Anápolis",
    "nicho": "Veterinária/Pet shop",
    "cidade": "Anápolis",
    "telefone": "+55 62 99361-8515",
    "redes_sociais": "@petstopanapoliss",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Clínica 24h; não foi localizado site com domínio próprio da unidade",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "sobrancelhas-isadora-lima-goiania",
    "nome": "Sobrancelhas Isadora Lima",
    "nicho": "Sobrancelhas/Micropigmentação",
    "cidade": "Goiânia",
    "telefone": "+55 62 98578-1754",
    "redes_sociais": "@sobrancelhasisadoralima",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone e Instagram confirmados via busca; endereço na Av Portugal Setor Oeste; sem site próprio encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "anna-karenina-sobrancelhas-goiania",
    "nome": "Anna Karenina Sobrancelhas",
    "nicho": "Sobrancelhas/Micropigmentação",
    "cidade": "Goiânia",
    "telefone": "+55 62 3225-2011",
    "redes_sociais": "@annakareninasobrancelhas",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone confirmado em diretórios (CNPJ/Econodata) e perfil Instagram localizado; sem site próprio dedicado encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "don-fernando-barbearia-goiania",
    "nome": "Don Fernando Barbearia",
    "nicho": "Barbearia",
    "cidade": "Goiânia",
    "telefone": "+55 62 98262-5344",
    "redes_sociais": "@donfernandobarbearia",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone e WhatsApp confirmados em diretórios, Instagram ativo; sem site próprio encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "marcao-barbearia-goiania",
    "nome": "Marcao Barbearia",
    "nicho": "Barbearia",
    "cidade": "Goiânia",
    "telefone": "+55 62 98172-4344",
    "redes_sociais": "@marcaobarbearia_",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone/WhatsApp e Instagram confirmados via busca; endereço no Setor Criméia Oeste; sem site próprio encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "oeste-barbearia-goiania",
    "nome": "Oeste Barbearia",
    "nicho": "Barbearia",
    "cidade": "Goiânia",
    "telefone": "+55 62 99275-5095",
    "redes_sociais": "@oestebarbeariaa",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "WhatsApp e Instagram confirmados; localizada no Setor Oeste; sem site próprio encontrado nos resultados",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "aninhas-nail-designer-anapolis",
    "nome": "Aninhas Nail Designer",
    "nicho": "Nail designer",
    "cidade": "Anápolis",
    "telefone": "+55 62 99401-3851",
    "redes_sociais": "@aninhas_naildesigner",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone confirmado em duas buscas independentes via página de agendamento apnt.app; Instagram confirmado; nenhum site próprio encontrado",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "studio-penelope-micropigmentacao-anapolis",
    "nome": "Studio Penélope Micropigmentação",
    "nicho": "Sobrancelhas/Micropigmentação",
    "cidade": "Anápolis",
    "telefone": "+55 62 98303-6205",
    "redes_sociais": "Facebook: Studio Penélope Micropigmentação",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone confirmado em três buscas independentes via diretórios locais; apenas Facebook e TikTok encontrados, sem site próprio",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "centro-odonto-anapolis",
    "nome": "Centro Odonto",
    "nicho": "Odontologia",
    "cidade": "Anápolis",
    "telefone": "+55 62 98503-7650",
    "redes_sociais": "",
    "avaliacao": 4.9,
    "n_avaliacoes": 79,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site próprio confirmado — aparece apenas em diretórios agregadores (Doctoralia, DentMap, Anápolis Club). Contato só por WhatsApp/telefone. Clínica independente, não é rede. Endereço: R. Luís França, 234 - Jundiaí, Anápolis - GO, 75110-760.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "poesia-arquitetura-anapolis",
    "nome": "Poesia Arquitetura",
    "nicho": "Arquitetura",
    "cidade": "Anápolis",
    "telefone": "+55 62 99306-6273",
    "redes_sociais": "linktr.ee/poesiaarquitetura",
    "avaliacao": 5,
    "n_avaliacoes": 13,
    "prioridade": "Alta",
    "site_confirmado": "Baixo",
    "status": "a_contatar",
    "observacoes": "Só Linktree, nenhum site dedicado encontrado. Escritório de arquitetura vive de mostrar projeto visualmente — Linktree não sustenta isso, fit forte pro portfólio/institucional. Endereço: London Eye Offices - Av. Sen. José Lourenço Dias - St. Central, Anápolis - GO, 75020-010.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "anderson-junio-arquiteto-e-urbanista-anapolis",
    "nome": "Anderson Junio Arquiteto e Urbanista",
    "nicho": "Arquitetura",
    "cidade": "Anápolis",
    "telefone": "+55 62 99466-0696",
    "redes_sociais": "@anderson_arquiteto",
    "avaliacao": 5,
    "n_avaliacoes": 26,
    "prioridade": "Alta",
    "site_confirmado": "Baixo",
    "status": "a_contatar",
    "observacoes": "Mais de 10 anos de mercado, atuação residencial/comercial/industrial. Sem site próprio — só Linktree (linktr.ee/andersonjunio_arq), Instagram com 2.107 seguidores, LinkedIn e Facebook. Junto com Poesia Arquitetura, indica arquitetos independentes em Anápolis sem site como nicho recorrente. Endereço: Condomínio Residencial Havilah - R. 22, Q. A - Nº 38, bloco 05, A44 - Chácaras Americanas, Anápolis - GO, 75103-205.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  },
  {
    "id": "pedro-xavier-advogados-anapolis",
    "nome": "Pedro Xavier Advogados",
    "nicho": "Advocacia",
    "cidade": "Anápolis",
    "telefone": "+55 62 3702-0999",
    "redes_sociais": "",
    "avaliacao": 4.9,
    "n_avaliacoes": 244,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site próprio confirmado — só diretórios jurídicos (Jusbrasil), registro CNPJ (CNPJ.biz) e Facebook modesto (113 curtidas). Negócio grande e ativo sem presença digital própria — bom fit pro pacote institucional: área de atuação, prova social (244 avaliações é argumento forte), contato direto. Endereço: R. do Carmo, 9 - Jundiaí, Anápolis - GO, 75113-050.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-15T02:48:56.635Z"
  }
];
