// Gerado por scripts/build-leads-seed.js a partir de data/leads_seed.csv
// Não edite à mão — rode o script novamente para atualizar.
const SEED_LEADS = [
  {
    "id": "viva-odonto-goiania",
    "nome": "Viva Odonto",
    "nicho": "Odontologia",
    "cidade": "Goiânia",
    "telefone": "+55 62 99983-9130",
    "redes_sociais": "@vivaodonto.goiania",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Sem site próprio confirmado via busca (apenas Instagram). Setor Goiânia Viva.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "plena-saude-e-beleza-anapolis",
    "nome": "Plena Saúde e Beleza",
    "nicho": "Estética",
    "cidade": "Anápolis",
    "telefone": "+55 62 99655-0988",
    "redes_sociais": "@plena.saudebeleza",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Clínica ativa desde 2005 (Plena Clínica Integrada de Medicina e Estética Ltda), Rua Barão do Rio Branco 573, Centro. Sem site próprio confirmado.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "spallita-anapolis",
    "nome": "Spallitá",
    "nicho": "Estética",
    "cidade": "Anápolis",
    "telefone": "+55 62 99314-3551",
    "redes_sociais": "@spallita",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Telefone fixo também: (62) 3706-1445. Sem site próprio confirmado (só Facebook/Instagram).",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "marfim-ambientes-goiania",
    "nome": "Marfim Ambientes",
    "nicho": "Marcenaria/Móveis planejados",
    "cidade": "Goiânia",
    "telefone": "+55 62 98643-0412",
    "redes_sociais": "@marfimambientes",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Móveis planejados alto padrão, atua em Goiânia/Aparecida de Goiânia. Sem site próprio confirmado.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "c-a-marmoraria-anapolis",
    "nome": "C&A Marmoraria",
    "nicho": "Marmoraria",
    "cidade": "Anápolis",
    "telefone": "+55 62 99306-3063",
    "redes_sociais": "",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Bairro de Lourdes/Centro. Só aparece em diretórios + WhatsApp, sem site próprio.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "marmoraria-anapolina-anapolis",
    "nome": "Marmoraria Anapolina",
    "nicho": "Marmoraria",
    "cidade": "Anápolis",
    "telefone": "+55 62 99297-4237",
    "redes_sociais": "@marmorariaanapolina",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Mais de 20 anos no mercado, CNPJ ativo. Sem site próprio confirmado (Facebook/Instagram).",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "marmoraria-brasil-anapolis",
    "nome": "Marmoraria Brasil",
    "nicho": "Marmoraria",
    "cidade": "Anápolis",
    "telefone": "+55 62 3771-3495",
    "redes_sociais": "@marmorariabrasill1",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Alta",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Av. Pedro Ludovico, 3049. Sem site próprio confirmado, só Instagram.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "marceneiro-goiania-goiania",
    "nome": "Marceneiro Goiânia",
    "nicho": "Marcenaria",
    "cidade": "Goiânia",
    "telefone": "+55 62 99232-8423",
    "redes_sociais": "",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "Mais de 30 anos no ramo. Site atual é uma página gratuita do Google Sites (sites.google.com) — conta como site de baixo nível, não site profissional.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "recanto-santa-cecilia-eventos-anapolis",
    "nome": "Recanto Santa Cecília Eventos",
    "nicho": "Buffet/Eventos",
    "cidade": "Anápolis",
    "telefone": "+55 62 99980-0221",
    "redes_sociais": "@recantosantacecilia",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Espaço para eventos. Sem site próprio confirmado, só Instagram.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  },
  {
    "id": "celebrare-casa-de-eventos-anapolis",
    "nome": "Celebrare Casa de Eventos",
    "nicho": "Buffet/Eventos",
    "cidade": "Anápolis",
    "telefone": "+55 62 99182-2474",
    "redes_sociais": "@celebrarecasadeventos",
    "avaliacao": null,
    "n_avaliacoes": null,
    "prioridade": "Média",
    "site_confirmado": "Não",
    "status": "a_contatar",
    "observacoes": "Aluguel de espaço para festas/eventos. Sem site próprio confirmado, só Instagram.",
    "origem": "pesquisa_web",
    "created_at": "2026-07-14T18:35:33.936Z"
  }
];
