// Gerado por scripts/build-leads-seed.js a partir de data/leads_seed.csv
// Não edite à mão — rode o script novamente para atualizar.
const SEED_LEADS = [
  {
    "id": "restaurante-cheiro-verde-pires-do-rio",
    "nome": "Restaurante Cheiro Verde",
    "nicho": "Restaurante",
    "cidade": "Pires do Rio",
    "telefone": "+55 64 99944-6680",
    "avaliacao": 4.2,
    "n_avaliacoes": 796,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "sabor-na-brasa-restaurante-e-churrascaria-pires-do-rio",
    "nome": "Sabor Na Brasa Restaurante E Churrascaria",
    "nicho": "Restaurante",
    "cidade": "Pires do Rio",
    "telefone": "+55 64 99967-6488",
    "avaliacao": 4.6,
    "n_avaliacoes": 92,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "caninde-gastrobar-pires-do-rio",
    "nome": "Canindé Gastrobar",
    "nicho": "Bar/Restaurante",
    "cidade": "Pires do Rio",
    "telefone": "",
    "avaliacao": 4.6,
    "n_avaliacoes": 189,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "churrascaria-imperio-do-churrasco-pires-do-rio",
    "nome": "Churrascaria Império do Churrasco",
    "nicho": "Restaurante",
    "cidade": "Pires do Rio",
    "telefone": "+55 64 99334-0107",
    "avaliacao": 4.6,
    "n_avaliacoes": 238,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "flor-de-sal-restaurante-e-eventos-pires-do-rio",
    "nome": "Flor De Sal Restaurante E Eventos",
    "nicho": "Restaurante/Eventos",
    "cidade": "Pires do Rio",
    "telefone": "",
    "avaliacao": 4.4,
    "n_avaliacoes": 29,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "taurus-gastrobar-pires-do-rio",
    "nome": "Taurus Gastrobar",
    "nicho": "Bar/Restaurante",
    "cidade": "Pires do Rio",
    "telefone": "+55 64 99203-4636",
    "avaliacao": 4.6,
    "n_avaliacoes": 459,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "estacionamento-atalaia-aeroporto-de-goiania-goiania",
    "nome": "Estacionamento Atalaia Aeroporto de Goiânia",
    "nicho": "Estacionamento",
    "cidade": "Goiânia",
    "telefone": "+55 62 98447-3752",
    "avaliacao": 5,
    "n_avaliacoes": 365,
    "prioridade": "Baixa",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "small-parking-estacionamento-aeroporto-goiania",
    "nome": "Small Parking Estacionamento Aeroporto",
    "nicho": "Estacionamento",
    "cidade": "Goiânia",
    "telefone": "+55 62 99898-7824",
    "avaliacao": 4.8,
    "n_avaliacoes": 1197,
    "prioridade": "Baixa",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "estacionamento-aero-parking-ltda-goiania",
    "nome": "Estacionamento Aero Parking Ltda",
    "nicho": "Estacionamento",
    "cidade": "Goiânia",
    "telefone": "+55 62 99979-4077",
    "avaliacao": 4.6,
    "n_avaliacoes": 143,
    "prioridade": "Baixa",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "estacionamento-carvalho-goiania",
    "nome": "Estacionamento Carvalho",
    "nicho": "Estacionamento",
    "cidade": "Goiânia",
    "telefone": "+55 62 99550-0949",
    "avaliacao": 5,
    "n_avaliacoes": 5,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "rapidopark-estacionamentos-e-servicos-goiania",
    "nome": "RAPIDOPARK ESTACIONAMENTOS E SERVICOS",
    "nicho": "Estacionamento",
    "cidade": "Goiânia",
    "telefone": "+55 62 3213-6214",
    "avaliacao": 3.5,
    "n_avaliacoes": 13,
    "prioridade": "Baixa",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "auto-mecanica-contorno-anapolis",
    "nome": "Auto Mecânica Contorno",
    "nicho": "Oficina mecânica",
    "cidade": "Anápolis",
    "telefone": "+55 62 3324-1534",
    "avaliacao": 4.5,
    "n_avaliacoes": 39,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "auto-mecanica-cometa-anapolis",
    "nome": "Auto Mecânica Cometa",
    "nicho": "Oficina mecânica",
    "cidade": "Anápolis",
    "telefone": "+55 62 99132-2470",
    "avaliacao": 4.9,
    "n_avaliacoes": 20,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "mecanica-leal-anapolis",
    "nome": "Mecânica Leal",
    "nicho": "Oficina mecânica",
    "cidade": "Anápolis",
    "telefone": "+55 62 99203-8993",
    "avaliacao": 4.8,
    "n_avaliacoes": 136,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "codicar-premium-centro-automotivo-anapolis",
    "nome": "Codicar Premium - Centro automotivo",
    "nicho": "Oficina mecânica",
    "cidade": "Anápolis",
    "telefone": "+55 62 98221-3965",
    "avaliacao": 4.9,
    "n_avaliacoes": 245,
    "prioridade": "Baixa",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "america-centro-automotivo-anapolis",
    "nome": "América Centro Automotivo",
    "nicho": "Oficina mecânica",
    "cidade": "Anápolis",
    "telefone": "+55 62 96000-7496",
    "avaliacao": 4.8,
    "n_avaliacoes": 66,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "w-1-servicos-automotivos-anapolis",
    "nome": "W-1 Serviços Automotivos",
    "nicho": "Oficina mecânica",
    "cidade": "Anápolis",
    "telefone": "+55 62 3099-3329",
    "avaliacao": 4.9,
    "n_avaliacoes": 69,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "studio-brunna-lorrayne-silvania",
    "nome": "Studio Brunna Lorrayne",
    "nicho": "Salão de beleza",
    "cidade": "Silvânia",
    "telefone": "+55 62 99478-1183",
    "avaliacao": 4.9,
    "n_avaliacoes": 36,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "bem-fast-silvania",
    "nome": "Bem Fast",
    "nicho": "Salão de beleza",
    "cidade": "Silvânia",
    "telefone": "+55 62 99698-7282",
    "avaliacao": 4.7,
    "n_avaliacoes": 7,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "spaco-nubia-cunha-silvania",
    "nome": "Spaço Núbia Cunha",
    "nicho": "Salão de beleza",
    "cidade": "Silvânia",
    "telefone": "+55 62 99973-2750",
    "avaliacao": 4.9,
    "n_avaliacoes": 10,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "atelie-cris-bueno-silvania",
    "nome": "Ateliê Cris Bueno",
    "nicho": "Ateliê/Loja",
    "cidade": "Silvânia",
    "telefone": "",
    "avaliacao": 4.9,
    "n_avaliacoes": 47,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "monte-centro-de-beleza-silvania",
    "nome": "Montê, centro de beleza",
    "nicho": "Salão de beleza",
    "cidade": "Silvânia",
    "telefone": "+55 62 99641-3619",
    "avaliacao": 4.8,
    "n_avaliacoes": 21,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "crisnalva-abreu-studio-beauty-silvania",
    "nome": "Crisnalva Abreu Studio Beauty",
    "nicho": "Salão de beleza",
    "cidade": "Silvânia",
    "telefone": "",
    "avaliacao": 4.9,
    "n_avaliacoes": 15,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "atacadao-de-ipameri-ipameri",
    "nome": "Atacadão de Ipameri",
    "nicho": "Atacado/Mercado",
    "cidade": "Ipameri",
    "telefone": "+55 64 3491-4996",
    "avaliacao": 4.3,
    "n_avaliacoes": 125,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "supermercado-veronica-ipameri",
    "nome": "Supermercado Verônica",
    "nicho": "Mercado",
    "cidade": "Ipameri",
    "telefone": "+55 64 3491-1360",
    "avaliacao": 4.1,
    "n_avaliacoes": 651,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "mercadao-universitario-ipameri",
    "nome": "Mercadão Universitário",
    "nicho": "Mercado",
    "cidade": "Ipameri",
    "telefone": "+55 64 99267-5459",
    "avaliacao": 4.3,
    "n_avaliacoes": 6,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "super-doni-ipameri",
    "nome": "Super Doni",
    "nicho": "Mercado",
    "cidade": "Ipameri",
    "telefone": "+55 64 3491-3750",
    "avaliacao": 4.5,
    "n_avaliacoes": 136,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "mega-bytes-distribuidora-ipameri",
    "nome": "Mega Bytes Distribuidora",
    "nicho": "Distribuidora/Mercado",
    "cidade": "Ipameri",
    "telefone": "+55 64 3491-4103",
    "avaliacao": 4.7,
    "n_avaliacoes": 83,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "supermercado-moreira-ipameri",
    "nome": "Supermercado Moreira",
    "nicho": "Mercado",
    "cidade": "Ipameri",
    "telefone": "+55 64 3491-3251",
    "avaliacao": 4.1,
    "n_avaliacoes": 127,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "borracharia-movel-pit-stop-catalao",
    "nome": "Borracharia Móvel Pit Stop",
    "nicho": "Borracharia",
    "cidade": "Catalão",
    "telefone": "+55 64 99934-9057",
    "avaliacao": 5,
    "n_avaliacoes": 5,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "borracharia-sao-joao-catalao",
    "nome": "Borracharia São João",
    "nicho": "Borracharia",
    "cidade": "Catalão",
    "telefone": "+55 64 99627-2006",
    "avaliacao": 5,
    "n_avaliacoes": 43,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "b20-borracharia-da-20-catalao",
    "nome": "B20 Borracharia da 20",
    "nicho": "Borracharia",
    "cidade": "Catalão",
    "telefone": "+55 64 3411-2016",
    "avaliacao": 3.7,
    "n_avaliacoes": 54,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "lihan-borracharia-movel-24-horas-catalao",
    "nome": "LIHAN BORRACHARIA MÓVEL 24 horas",
    "nicho": "Borracharia",
    "cidade": "Catalão",
    "telefone": "+55 64 98154-8109",
    "avaliacao": 4.8,
    "n_avaliacoes": 28,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "borracharia-araguaia-catalao",
    "nome": "Borracharia Araguaia",
    "nicho": "Borracharia",
    "cidade": "Catalão",
    "telefone": "+55 64 99972-5734",
    "avaliacao": 4.5,
    "n_avaliacoes": 33,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "pneucar-borracharia-movel-catalao",
    "nome": "Pneucar Borracharia Móvel",
    "nicho": "Borracharia",
    "cidade": "Catalão",
    "telefone": "+55 64 99926-5305",
    "avaliacao": 5,
    "n_avaliacoes": 4,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "pluma-pets-orizona",
    "nome": "Pluma pets",
    "nicho": "Pet shop",
    "cidade": "Orizona",
    "telefone": "+55 64 99946-6095",
    "avaliacao": 5,
    "n_avaliacoes": 1,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "pet-vida-consultorio-veterinario-orizona",
    "nome": "Pet Vida Consultório Veterinário",
    "nicho": "Veterinária",
    "cidade": "Orizona",
    "telefone": "+55 64 99978-0922",
    "avaliacao": 5,
    "n_avaliacoes": 13,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "pesca-pet-orizona",
    "nome": "PESCA & PET",
    "nicho": "Pet/Pesca",
    "cidade": "Orizona",
    "telefone": "+55 64 99929-4817",
    "avaliacao": 3.7,
    "n_avaliacoes": 3,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "proagro-orizona",
    "nome": "Proagro",
    "nicho": "Agropecuária/Pet",
    "cidade": "Orizona",
    "telefone": "+55 64 3474-2362",
    "avaliacao": 5,
    "n_avaliacoes": 1,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "casa-do-produtor-orizona",
    "nome": "Casa do Produtor",
    "nicho": "Agropecuária",
    "cidade": "Orizona",
    "telefone": "+55 64 3474-1528",
    "avaliacao": 4.5,
    "n_avaliacoes": 91,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "salao-da-vera-orizona",
    "nome": "Salão da Vera",
    "nicho": "Pet (banho e tosa)",
    "cidade": "Orizona",
    "telefone": "+55 64 3474-1849",
    "avaliacao": 5,
    "n_avaliacoes": 1,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "carminha-distribuidora-e-conveniencia-morrinhos",
    "nome": "CARMINHA DISTRIBUIDORA E CONVENIÊNCIA",
    "nicho": "Distribuidora",
    "cidade": "Morrinhos",
    "telefone": "+55 64 99245-5447",
    "avaliacao": 4.6,
    "n_avaliacoes": 121,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "rema-distribuidora-morrinhos",
    "nome": "Rema Distribuidora",
    "nicho": "Distribuidora",
    "cidade": "Morrinhos",
    "telefone": "+55 64 3047-1132",
    "avaliacao": 4.1,
    "n_avaliacoes": 28,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "revenda-pereira-ambev-morrinhos",
    "nome": "Revenda Pereira - AmBev",
    "nicho": "Distribuidora (marca)",
    "cidade": "Morrinhos",
    "telefone": "+55 64 3413-1740",
    "avaliacao": 4.6,
    "n_avaliacoes": 48,
    "prioridade": "Baixa",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "edu-gas-agua-morrinhos",
    "nome": "EDU GÁS & ÁGUA",
    "nicho": "Distribuidora",
    "cidade": "Morrinhos",
    "telefone": "+55 64 99985-4279",
    "avaliacao": 5,
    "n_avaliacoes": 5,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "mercearia-distribuidora-arca-de-noe-morrinhos",
    "nome": "Mercearia & Distribuidora Arca de Noé",
    "nicho": "Mercearia",
    "cidade": "Morrinhos",
    "telefone": "",
    "avaliacao": 4.9,
    "n_avaliacoes": 8,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "distribuidora-e-lanchonete-moura-morrinhos",
    "nome": "Distribuidora e lanchonete Moura",
    "nicho": "Distribuidora/Lanchonete",
    "cidade": "Morrinhos",
    "telefone": "+55 64 99601-7872",
    "avaliacao": 4.7,
    "n_avaliacoes": 18,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "sky-fit-academia-caldas-novas",
    "nome": "Sky Fit – Academia",
    "nicho": "Academia",
    "cidade": "Caldas Novas",
    "telefone": "+55 64 99320-1422",
    "avaliacao": 4.4,
    "n_avaliacoes": 12,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "academia-wolf-gym-cn-caldas-novas",
    "nome": "Academia Wolf Gym CN",
    "nicho": "Academia",
    "cidade": "Caldas Novas",
    "telefone": "+55 64 99343-5837",
    "avaliacao": 4.9,
    "n_avaliacoes": 249,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "mum-fitness-academia-caldas-novas",
    "nome": "Mum Fitness Academia",
    "nicho": "Academia",
    "cidade": "Caldas Novas",
    "telefone": "+55 64 99215-5030",
    "avaliacao": 4.9,
    "n_avaliacoes": 136,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "basic-fit-caldas-novas-caldas-novas",
    "nome": "Basic Fit - Caldas Novas",
    "nicho": "Academia (rede)",
    "cidade": "Caldas Novas",
    "telefone": "+55 64 99236-3092",
    "avaliacao": 5,
    "n_avaliacoes": 33,
    "prioridade": "Baixa",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "centro-de-treinamento-arena-fitness-caldas-novas",
    "nome": "Centro de Treinamento Arena Fitness",
    "nicho": "Academia",
    "cidade": "Caldas Novas",
    "telefone": "+55 64 99206-8118",
    "avaliacao": 4.8,
    "n_avaliacoes": 73,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "academia-thermas-fit-caldas-novas",
    "nome": "Academia Thermas Fit",
    "nicho": "Academia",
    "cidade": "Caldas Novas",
    "telefone": "+55 64 99226-5000",
    "avaliacao": 4.5,
    "n_avaliacoes": 238,
    "prioridade": "Média",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "mega-opcao-presentes-brinquedos-papelaria-vianopolis",
    "nome": "Mega Opção (Presentes/Brinquedos/Papelaria)",
    "nicho": "Papelaria/Loja",
    "cidade": "Vianópolis",
    "telefone": "+55 62 3335-2417",
    "avaliacao": 4.6,
    "n_avaliacoes": 13,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "aquarela-papelaria-vianopolis",
    "nome": "Aquarela Papelaria",
    "nicho": "Papelaria",
    "cidade": "Vianópolis",
    "telefone": "+55 62 98590-5571",
    "avaliacao": 5,
    "n_avaliacoes": 3,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "styllus-papelaria-e-decoracoes-vianopolis",
    "nome": "STYLLUS Papelaria e Decorações",
    "nicho": "Papelaria",
    "cidade": "Vianópolis",
    "telefone": "+55 62 99945-8270",
    "avaliacao": 4,
    "n_avaliacoes": 3,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "ferreira-importados-vianopolis-vianopolis",
    "nome": "Ferreira Importados Vianópolis",
    "nicho": "Loja (artigos de pesca)",
    "cidade": "Vianópolis",
    "telefone": "+55 62 99912-8885",
    "avaliacao": 4,
    "n_avaliacoes": 3,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  },
  {
    "id": "atelie-real-alice-vianopolis",
    "nome": "Ateliê Real Alice",
    "nicho": "Ateliê/Loja",
    "cidade": "Vianópolis",
    "telefone": "+55 62 98144-5060",
    "avaliacao": 4.8,
    "n_avaliacoes": 12,
    "prioridade": "Alta",
    "site_confirmado": "A verificar",
    "status": "a_contatar",
    "observacoes": "",
    "origem": "google_maps",
    "created_at": "2026-07-14T01:22:17.036Z"
  }
];
